// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.anteoy.service.usercenter;

public interface AcceleratesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.Accelerates)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string accelerateLine = 2;</code>
   */
  java.lang.String getAccelerateLine();
  /**
   * <code>string accelerateLine = 2;</code>
   */
  com.google.protobuf.ByteString
      getAccelerateLineBytes();

  /**
   * <code>string monitorWebsocket = 3;</code>
   */
  java.lang.String getMonitorWebsocket();
  /**
   * <code>string monitorWebsocket = 3;</code>
   */
  com.google.protobuf.ByteString
      getMonitorWebsocketBytes();

  /**
   * <code>string classWebsocket = 4;</code>
   */
  java.lang.String getClassWebsocket();
  /**
   * <code>string classWebsocket = 4;</code>
   */
  com.google.protobuf.ByteString
      getClassWebsocketBytes();

  /**
   * <code>string httpServer = 5;</code>
   */
  java.lang.String getHttpServer();
  /**
   * <code>string httpServer = 5;</code>
   */
  com.google.protobuf.ByteString
      getHttpServerBytes();

  /**
   * <code>string janusServer = 6;</code>
   */
  java.lang.String getJanusServer();
  /**
   * <code>string janusServer = 6;</code>
   */
  com.google.protobuf.ByteString
      getJanusServerBytes();
}
