// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.anteoy.service.usercenter;

public interface CascadeStuGRPCsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.CascadeStuGRPCs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .custom_proto.CascadeStuGRPC sls = 1;</code>
   */
  java.util.List<CascadeStuGRPC>
      getSlsList();
  /**
   * <code>repeated .custom_proto.CascadeStuGRPC sls = 1;</code>
   */
  CascadeStuGRPC getSls(int index);
  /**
   * <code>repeated .custom_proto.CascadeStuGRPC sls = 1;</code>
   */
  int getSlsCount();
  /**
   * <code>repeated .custom_proto.CascadeStuGRPC sls = 1;</code>
   */
  java.util.List<? extends CascadeStuGRPCOrBuilder>
      getSlsOrBuilderList();
  /**
   * <code>repeated .custom_proto.CascadeStuGRPC sls = 1;</code>
   */
  CascadeStuGRPCOrBuilder getSlsOrBuilder(
      int index);

  /**
   * <code>int64 total = 2;</code>
   */
  long getTotal();
}
