// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.anteoy.service.usercenter;

public interface GetTeacherInfoByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.GetTeacherInfoByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();
}
