// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.anteoy.service.usercenter;

/**
 * Protobuf type {@code custom_proto.RepGetCityByProvince}
 */
public  final class RepGetCityByProvince extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:custom_proto.RepGetCityByProvince)
    RepGetCityByProvinceOrBuilder {
  // Use RepGetCityByProvince.newBuilder() to construct.
  private RepGetCityByProvince(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RepGetCityByProvince() {
    citys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RepGetCityByProvince(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              citys_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            citys_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        citys_ = citys_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return UserCenterProto.internal_static_custom_proto_RepGetCityByProvince_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return UserCenterProto.internal_static_custom_proto_RepGetCityByProvince_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RepGetCityByProvince.class, RepGetCityByProvince.Builder.class);
  }

  public static final int CITYS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList citys_;
  /**
   * <code>repeated string citys = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getCitysList() {
    return citys_;
  }
  /**
   * <code>repeated string citys = 1;</code>
   */
  public int getCitysCount() {
    return citys_.size();
  }
  /**
   * <code>repeated string citys = 1;</code>
   */
  public java.lang.String getCitys(int index) {
    return citys_.get(index);
  }
  /**
   * <code>repeated string citys = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCitysBytes(int index) {
    return citys_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < citys_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, citys_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < citys_.size(); i++) {
        dataSize += computeStringSizeNoTag(citys_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCitysList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RepGetCityByProvince)) {
      return super.equals(obj);
    }
    RepGetCityByProvince other = (RepGetCityByProvince) obj;

    boolean result = true;
    result = result && getCitysList()
        .equals(other.getCitysList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCitysCount() > 0) {
      hash = (37 * hash) + CITYS_FIELD_NUMBER;
      hash = (53 * hash) + getCitysList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RepGetCityByProvince parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RepGetCityByProvince parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RepGetCityByProvince parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RepGetCityByProvince parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RepGetCityByProvince parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RepGetCityByProvince parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RepGetCityByProvince parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RepGetCityByProvince parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RepGetCityByProvince parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RepGetCityByProvince parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RepGetCityByProvince prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code custom_proto.RepGetCityByProvince}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:custom_proto.RepGetCityByProvince)
          RepGetCityByProvinceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserCenterProto.internal_static_custom_proto_RepGetCityByProvince_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserCenterProto.internal_static_custom_proto_RepGetCityByProvince_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RepGetCityByProvince.class, RepGetCityByProvince.Builder.class);
    }

    // Construct using RepGetCityByProvince.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      citys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return UserCenterProto.internal_static_custom_proto_RepGetCityByProvince_descriptor;
    }

    public RepGetCityByProvince getDefaultInstanceForType() {
      return RepGetCityByProvince.getDefaultInstance();
    }

    public RepGetCityByProvince build() {
      RepGetCityByProvince result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public RepGetCityByProvince buildPartial() {
      RepGetCityByProvince result = new RepGetCityByProvince(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        citys_ = citys_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.citys_ = citys_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RepGetCityByProvince) {
        return mergeFrom((RepGetCityByProvince)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RepGetCityByProvince other) {
      if (other == RepGetCityByProvince.getDefaultInstance()) return this;
      if (!other.citys_.isEmpty()) {
        if (citys_.isEmpty()) {
          citys_ = other.citys_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCitysIsMutable();
          citys_.addAll(other.citys_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RepGetCityByProvince parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RepGetCityByProvince) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList citys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCitysIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        citys_ = new com.google.protobuf.LazyStringArrayList(citys_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string citys = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCitysList() {
      return citys_.getUnmodifiableView();
    }
    /**
     * <code>repeated string citys = 1;</code>
     */
    public int getCitysCount() {
      return citys_.size();
    }
    /**
     * <code>repeated string citys = 1;</code>
     */
    public java.lang.String getCitys(int index) {
      return citys_.get(index);
    }
    /**
     * <code>repeated string citys = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCitysBytes(int index) {
      return citys_.getByteString(index);
    }
    /**
     * <code>repeated string citys = 1;</code>
     */
    public Builder setCitys(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCitysIsMutable();
      citys_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string citys = 1;</code>
     */
    public Builder addCitys(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCitysIsMutable();
      citys_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string citys = 1;</code>
     */
    public Builder addAllCitys(
        java.lang.Iterable<java.lang.String> values) {
      ensureCitysIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, citys_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string citys = 1;</code>
     */
    public Builder clearCitys() {
      citys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string citys = 1;</code>
     */
    public Builder addCitysBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCitysIsMutable();
      citys_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:custom_proto.RepGetCityByProvince)
  }

  // @@protoc_insertion_point(class_scope:custom_proto.RepGetCityByProvince)
  private static final RepGetCityByProvince DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RepGetCityByProvince();
  }

  public static RepGetCityByProvince getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RepGetCityByProvince>
      PARSER = new com.google.protobuf.AbstractParser<RepGetCityByProvince>() {
    public RepGetCityByProvince parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RepGetCityByProvince(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RepGetCityByProvince> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RepGetCityByProvince> getParserForType() {
    return PARSER;
  }

  public RepGetCityByProvince getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

