// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.anteoy.service.usercenter;

public interface RepGetforeignerByNickNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.RepGetforeignerByNickName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.custom_proto.RequestRTeacherStruct teacher = 1;</code>
   */
  boolean hasTeacher();
  /**
   * <code>.custom_proto.RequestRTeacherStruct teacher = 1;</code>
   */
  RequestRTeacherStruct getTeacher();
  /**
   * <code>.custom_proto.RequestRTeacherStruct teacher = 1;</code>
   */
  RequestRTeacherStructOrBuilder getTeacherOrBuilder();
}
