// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.anteoy.service.usercenter;

/**
 * Protobuf type {@code custom_proto.ReplyGetStudentIDsBySchoolGrade}
 */
public  final class ReplyGetStudentIDsBySchoolGrade extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:custom_proto.ReplyGetStudentIDsBySchoolGrade)
    ReplyGetStudentIDsBySchoolGradeOrBuilder {
  // Use ReplyGetStudentIDsBySchoolGrade.newBuilder() to construct.
  private ReplyGetStudentIDsBySchoolGrade(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReplyGetStudentIDsBySchoolGrade() {
    uids_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ReplyGetStudentIDsBySchoolGrade(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              uids_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000001;
            }
            uids_.add(input.readInt64());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              uids_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              uids_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        uids_ = java.util.Collections.unmodifiableList(uids_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return UserCenterProto.internal_static_custom_proto_ReplyGetStudentIDsBySchoolGrade_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return UserCenterProto.internal_static_custom_proto_ReplyGetStudentIDsBySchoolGrade_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ReplyGetStudentIDsBySchoolGrade.class, ReplyGetStudentIDsBySchoolGrade.Builder.class);
  }

  public static final int UIDS_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Long> uids_;
  /**
   * <code>repeated int64 uids = 1;</code>
   */
  public java.util.List<java.lang.Long>
      getUidsList() {
    return uids_;
  }
  /**
   * <code>repeated int64 uids = 1;</code>
   */
  public int getUidsCount() {
    return uids_.size();
  }
  /**
   * <code>repeated int64 uids = 1;</code>
   */
  public long getUids(int index) {
    return uids_.get(index);
  }
  private int uidsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getUidsList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(uidsMemoizedSerializedSize);
    }
    for (int i = 0; i < uids_.size(); i++) {
      output.writeInt64NoTag(uids_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < uids_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(uids_.get(i));
      }
      size += dataSize;
      if (!getUidsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      uidsMemoizedSerializedSize = dataSize;
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ReplyGetStudentIDsBySchoolGrade)) {
      return super.equals(obj);
    }
    ReplyGetStudentIDsBySchoolGrade other = (ReplyGetStudentIDsBySchoolGrade) obj;

    boolean result = true;
    result = result && getUidsList()
        .equals(other.getUidsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUidsCount() > 0) {
      hash = (37 * hash) + UIDS_FIELD_NUMBER;
      hash = (53 * hash) + getUidsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ReplyGetStudentIDsBySchoolGrade parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ReplyGetStudentIDsBySchoolGrade parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ReplyGetStudentIDsBySchoolGrade parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ReplyGetStudentIDsBySchoolGrade parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ReplyGetStudentIDsBySchoolGrade parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ReplyGetStudentIDsBySchoolGrade parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ReplyGetStudentIDsBySchoolGrade parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ReplyGetStudentIDsBySchoolGrade parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ReplyGetStudentIDsBySchoolGrade parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ReplyGetStudentIDsBySchoolGrade parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ReplyGetStudentIDsBySchoolGrade prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code custom_proto.ReplyGetStudentIDsBySchoolGrade}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:custom_proto.ReplyGetStudentIDsBySchoolGrade)
          ReplyGetStudentIDsBySchoolGradeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserCenterProto.internal_static_custom_proto_ReplyGetStudentIDsBySchoolGrade_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserCenterProto.internal_static_custom_proto_ReplyGetStudentIDsBySchoolGrade_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReplyGetStudentIDsBySchoolGrade.class, ReplyGetStudentIDsBySchoolGrade.Builder.class);
    }

    // Construct using ReplyGetStudentIDsBySchoolGrade.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      uids_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return UserCenterProto.internal_static_custom_proto_ReplyGetStudentIDsBySchoolGrade_descriptor;
    }

    public ReplyGetStudentIDsBySchoolGrade getDefaultInstanceForType() {
      return ReplyGetStudentIDsBySchoolGrade.getDefaultInstance();
    }

    public ReplyGetStudentIDsBySchoolGrade build() {
      ReplyGetStudentIDsBySchoolGrade result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ReplyGetStudentIDsBySchoolGrade buildPartial() {
      ReplyGetStudentIDsBySchoolGrade result = new ReplyGetStudentIDsBySchoolGrade(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        uids_ = java.util.Collections.unmodifiableList(uids_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.uids_ = uids_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ReplyGetStudentIDsBySchoolGrade) {
        return mergeFrom((ReplyGetStudentIDsBySchoolGrade)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ReplyGetStudentIDsBySchoolGrade other) {
      if (other == ReplyGetStudentIDsBySchoolGrade.getDefaultInstance()) return this;
      if (!other.uids_.isEmpty()) {
        if (uids_.isEmpty()) {
          uids_ = other.uids_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureUidsIsMutable();
          uids_.addAll(other.uids_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ReplyGetStudentIDsBySchoolGrade parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ReplyGetStudentIDsBySchoolGrade) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Long> uids_ = java.util.Collections.emptyList();
    private void ensureUidsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        uids_ = new java.util.ArrayList<java.lang.Long>(uids_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 uids = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getUidsList() {
      return java.util.Collections.unmodifiableList(uids_);
    }
    /**
     * <code>repeated int64 uids = 1;</code>
     */
    public int getUidsCount() {
      return uids_.size();
    }
    /**
     * <code>repeated int64 uids = 1;</code>
     */
    public long getUids(int index) {
      return uids_.get(index);
    }
    /**
     * <code>repeated int64 uids = 1;</code>
     */
    public Builder setUids(
        int index, long value) {
      ensureUidsIsMutable();
      uids_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 uids = 1;</code>
     */
    public Builder addUids(long value) {
      ensureUidsIsMutable();
      uids_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 uids = 1;</code>
     */
    public Builder addAllUids(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureUidsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, uids_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 uids = 1;</code>
     */
    public Builder clearUids() {
      uids_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:custom_proto.ReplyGetStudentIDsBySchoolGrade)
  }

  // @@protoc_insertion_point(class_scope:custom_proto.ReplyGetStudentIDsBySchoolGrade)
  private static final ReplyGetStudentIDsBySchoolGrade DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ReplyGetStudentIDsBySchoolGrade();
  }

  public static ReplyGetStudentIDsBySchoolGrade getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReplyGetStudentIDsBySchoolGrade>
      PARSER = new com.google.protobuf.AbstractParser<ReplyGetStudentIDsBySchoolGrade>() {
    public ReplyGetStudentIDsBySchoolGrade parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReplyGetStudentIDsBySchoolGrade(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReplyGetStudentIDsBySchoolGrade> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReplyGetStudentIDsBySchoolGrade> getParserForType() {
    return PARSER;
  }

  public ReplyGetStudentIDsBySchoolGrade getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

