// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.anteoy.service.usercenter;

public interface ReplyGetClassesStructOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.ReplyGetClassesStruct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string code = 2;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>repeated .custom_proto.ClassIdName sls = 3;</code>
   */
  java.util.List<ClassIdName>
      getSlsList();
  /**
   * <code>repeated .custom_proto.ClassIdName sls = 3;</code>
   */
  ClassIdName getSls(int index);
  /**
   * <code>repeated .custom_proto.ClassIdName sls = 3;</code>
   */
  int getSlsCount();
  /**
   * <code>repeated .custom_proto.ClassIdName sls = 3;</code>
   */
  java.util.List<? extends ClassIdNameOrBuilder>
      getSlsOrBuilderList();
  /**
   * <code>repeated .custom_proto.ClassIdName sls = 3;</code>
   */
  ClassIdNameOrBuilder getSlsOrBuilder(
      int index);
}
