// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.anteoy.service.usercenter;

public interface ReplyRStructOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.ReplyRStruct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   *200 注册成功 401 注册失败（用户原因） 500 服务器内部错误
   * </pre>
   *
   * <code>string code = 2;</code>
   */
  java.lang.String getCode();
  /**
   * <pre>
   *200 注册成功 401 注册失败（用户原因） 500 服务器内部错误
   * </pre>
   *
   * <code>string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>int64 id = 3;</code>
   */
  long getId();
}
