// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.anteoy.service.usercenter;

public interface ReqGetSchInfoByIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.ReqGetSchInfoByID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 schID = 1;</code>
   */
  long getSchID();
}
