// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.anteoy.service.usercenter;

public interface RequestSchoolCMSOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.RequestSchoolCMS)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string province = 1;</code>
   */
  java.lang.String getProvince();
  /**
   * <code>string province = 1;</code>
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <code>string city = 2;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 2;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string region_name = 3;</code>
   */
  java.lang.String getRegionName();
  /**
   * <code>string region_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getRegionNameBytes();
}
