// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.anteoy.service.usercenter;

public interface RequestGetTeaassisOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.RequestGetTeaassis)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 pageSize = 1;</code>
   */
  long getPageSize();

  /**
   * <pre>
   * 搜索条件
   * </pre>
   *
   * <code>int64 currentPage = 2;</code>
   */
  long getCurrentPage();
}
