// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.anteoy.service.usercenter;

/**
 * Protobuf type {@code custom_proto.RequestGetSchs}
 */
public  final class RequestGetSchs extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:custom_proto.RequestGetSchs)
    RequestGetSchsOrBuilder {
  // Use RequestGetSchs.newBuilder() to construct.
  private RequestGetSchs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestGetSchs() {
    pageSize_ = 0L;
    currentPage_ = 0L;
    searchName_ = "";
    extraFlag_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RequestGetSchs(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            pageSize_ = input.readInt64();
            break;
          }
          case 16: {

            currentPage_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            searchName_ = s;
            break;
          }
          case 32: {

            extraFlag_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return UserCenterProto.internal_static_custom_proto_RequestGetSchs_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return UserCenterProto.internal_static_custom_proto_RequestGetSchs_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RequestGetSchs.class, RequestGetSchs.Builder.class);
  }

  public static final int PAGESIZE_FIELD_NUMBER = 1;
  private long pageSize_;
  /**
   * <code>int64 pageSize = 1;</code>
   */
  public long getPageSize() {
    return pageSize_;
  }

  public static final int CURRENTPAGE_FIELD_NUMBER = 2;
  private long currentPage_;
  /**
   * <code>int64 currentPage = 2;</code>
   */
  public long getCurrentPage() {
    return currentPage_;
  }

  public static final int SEARCHNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object searchName_;
  /**
   * <pre>
   * 搜索条件
   * </pre>
   *
   * <code>string searchName = 3;</code>
   */
  public java.lang.String getSearchName() {
    java.lang.Object ref = searchName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      searchName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 搜索条件
   * </pre>
   *
   * <code>string searchName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSearchNameBytes() {
    java.lang.Object ref = searchName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      searchName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTRAFLAG_FIELD_NUMBER = 4;
  private long extraFlag_;
  /**
   * <pre>
   *额外搜索条件
   * </pre>
   *
   * <code>int64 ExtraFlag = 4;</code>
   */
  public long getExtraFlag() {
    return extraFlag_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pageSize_ != 0L) {
      output.writeInt64(1, pageSize_);
    }
    if (currentPage_ != 0L) {
      output.writeInt64(2, currentPage_);
    }
    if (!getSearchNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, searchName_);
    }
    if (extraFlag_ != 0L) {
      output.writeInt64(4, extraFlag_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pageSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, pageSize_);
    }
    if (currentPage_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, currentPage_);
    }
    if (!getSearchNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, searchName_);
    }
    if (extraFlag_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, extraFlag_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RequestGetSchs)) {
      return super.equals(obj);
    }
    RequestGetSchs other = (RequestGetSchs) obj;

    boolean result = true;
    result = result && (getPageSize()
        == other.getPageSize());
    result = result && (getCurrentPage()
        == other.getCurrentPage());
    result = result && getSearchName()
        .equals(other.getSearchName());
    result = result && (getExtraFlag()
        == other.getExtraFlag());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPageSize());
    hash = (37 * hash) + CURRENTPAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentPage());
    hash = (37 * hash) + SEARCHNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSearchName().hashCode();
    hash = (37 * hash) + EXTRAFLAG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExtraFlag());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RequestGetSchs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RequestGetSchs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RequestGetSchs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RequestGetSchs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RequestGetSchs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RequestGetSchs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RequestGetSchs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RequestGetSchs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RequestGetSchs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RequestGetSchs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RequestGetSchs prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code custom_proto.RequestGetSchs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:custom_proto.RequestGetSchs)
          RequestGetSchsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserCenterProto.internal_static_custom_proto_RequestGetSchs_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserCenterProto.internal_static_custom_proto_RequestGetSchs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestGetSchs.class, RequestGetSchs.Builder.class);
    }

    // Construct using RequestGetSchs.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      pageSize_ = 0L;

      currentPage_ = 0L;

      searchName_ = "";

      extraFlag_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return UserCenterProto.internal_static_custom_proto_RequestGetSchs_descriptor;
    }

    public RequestGetSchs getDefaultInstanceForType() {
      return RequestGetSchs.getDefaultInstance();
    }

    public RequestGetSchs build() {
      RequestGetSchs result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public RequestGetSchs buildPartial() {
      RequestGetSchs result = new RequestGetSchs(this);
      result.pageSize_ = pageSize_;
      result.currentPage_ = currentPage_;
      result.searchName_ = searchName_;
      result.extraFlag_ = extraFlag_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RequestGetSchs) {
        return mergeFrom((RequestGetSchs)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RequestGetSchs other) {
      if (other == RequestGetSchs.getDefaultInstance()) return this;
      if (other.getPageSize() != 0L) {
        setPageSize(other.getPageSize());
      }
      if (other.getCurrentPage() != 0L) {
        setCurrentPage(other.getCurrentPage());
      }
      if (!other.getSearchName().isEmpty()) {
        searchName_ = other.searchName_;
        onChanged();
      }
      if (other.getExtraFlag() != 0L) {
        setExtraFlag(other.getExtraFlag());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RequestGetSchs parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RequestGetSchs) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long pageSize_ ;
    /**
     * <code>int64 pageSize = 1;</code>
     */
    public long getPageSize() {
      return pageSize_;
    }
    /**
     * <code>int64 pageSize = 1;</code>
     */
    public Builder setPageSize(long value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 pageSize = 1;</code>
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0L;
      onChanged();
      return this;
    }

    private long currentPage_ ;
    /**
     * <code>int64 currentPage = 2;</code>
     */
    public long getCurrentPage() {
      return currentPage_;
    }
    /**
     * <code>int64 currentPage = 2;</code>
     */
    public Builder setCurrentPage(long value) {
      
      currentPage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 currentPage = 2;</code>
     */
    public Builder clearCurrentPage() {
      
      currentPage_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object searchName_ = "";
    /**
     * <pre>
     * 搜索条件
     * </pre>
     *
     * <code>string searchName = 3;</code>
     */
    public java.lang.String getSearchName() {
      java.lang.Object ref = searchName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        searchName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 搜索条件
     * </pre>
     *
     * <code>string searchName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSearchNameBytes() {
      java.lang.Object ref = searchName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        searchName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 搜索条件
     * </pre>
     *
     * <code>string searchName = 3;</code>
     */
    public Builder setSearchName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      searchName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 搜索条件
     * </pre>
     *
     * <code>string searchName = 3;</code>
     */
    public Builder clearSearchName() {
      
      searchName_ = getDefaultInstance().getSearchName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 搜索条件
     * </pre>
     *
     * <code>string searchName = 3;</code>
     */
    public Builder setSearchNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      searchName_ = value;
      onChanged();
      return this;
    }

    private long extraFlag_ ;
    /**
     * <pre>
     *额外搜索条件
     * </pre>
     *
     * <code>int64 ExtraFlag = 4;</code>
     */
    public long getExtraFlag() {
      return extraFlag_;
    }
    /**
     * <pre>
     *额外搜索条件
     * </pre>
     *
     * <code>int64 ExtraFlag = 4;</code>
     */
    public Builder setExtraFlag(long value) {
      
      extraFlag_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *额外搜索条件
     * </pre>
     *
     * <code>int64 ExtraFlag = 4;</code>
     */
    public Builder clearExtraFlag() {
      
      extraFlag_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:custom_proto.RequestGetSchs)
  }

  // @@protoc_insertion_point(class_scope:custom_proto.RequestGetSchs)
  private static final RequestGetSchs DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RequestGetSchs();
  }

  public static RequestGetSchs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestGetSchs>
      PARSER = new com.google.protobuf.AbstractParser<RequestGetSchs>() {
    public RequestGetSchs parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestGetSchs(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestGetSchs> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestGetSchs> getParserForType() {
    return PARSER;
  }

  public RequestGetSchs getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

