// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.anteoy.service.usercenter;

public interface TextbookVersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.TextbookVersion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 Id = 1;</code>
   */
  long getId();

  /**
   * <code>string version = 2;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 2;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
