// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

public interface CascadeStuGRPCsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.CascadeStuGRPCs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .custom_proto.CascadeStuGRPC sls = 1;</code>
   */
  java.util.List<com.class100.service.usercenter.CascadeStuGRPC> 
      getSlsList();
  /**
   * <code>repeated .custom_proto.CascadeStuGRPC sls = 1;</code>
   */
  com.class100.service.usercenter.CascadeStuGRPC getSls(int index);
  /**
   * <code>repeated .custom_proto.CascadeStuGRPC sls = 1;</code>
   */
  int getSlsCount();
  /**
   * <code>repeated .custom_proto.CascadeStuGRPC sls = 1;</code>
   */
  java.util.List<? extends com.class100.service.usercenter.CascadeStuGRPCOrBuilder> 
      getSlsOrBuilderList();
  /**
   * <code>repeated .custom_proto.CascadeStuGRPC sls = 1;</code>
   */
  com.class100.service.usercenter.CascadeStuGRPCOrBuilder getSlsOrBuilder(
      int index);

  /**
   * <code>int64 total = 2;</code>
   */
  long getTotal();
}
