// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

public interface RepCreateAccelerateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.RepCreateAccelerate)
    com.google.protobuf.MessageOrBuilder {
}
