// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

public interface RepGetClassBySchoolDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.RepGetClassBySchoolD)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.custom_proto.RequestRClassStruct ClassSch = 1;</code>
   */
  boolean hasClassSch();
  /**
   * <code>.custom_proto.RequestRClassStruct ClassSch = 1;</code>
   */
  com.class100.service.usercenter.RequestRClassStruct getClassSch();
  /**
   * <code>.custom_proto.RequestRClassStruct ClassSch = 1;</code>
   */
  com.class100.service.usercenter.RequestRClassStructOrBuilder getClassSchOrBuilder();
}
