// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

public interface Reply_MySchoolmate_appOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.Reply_MySchoolmate_app)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .custom_proto.Reply_MySchoolmate myschoolmate = 1;</code>
   */
  java.util.List<com.class100.service.usercenter.Reply_MySchoolmate> 
      getMyschoolmateList();
  /**
   * <code>repeated .custom_proto.Reply_MySchoolmate myschoolmate = 1;</code>
   */
  com.class100.service.usercenter.Reply_MySchoolmate getMyschoolmate(int index);
  /**
   * <code>repeated .custom_proto.Reply_MySchoolmate myschoolmate = 1;</code>
   */
  int getMyschoolmateCount();
  /**
   * <code>repeated .custom_proto.Reply_MySchoolmate myschoolmate = 1;</code>
   */
  java.util.List<? extends com.class100.service.usercenter.Reply_MySchoolmateOrBuilder> 
      getMyschoolmateOrBuilderList();
  /**
   * <code>repeated .custom_proto.Reply_MySchoolmate myschoolmate = 1;</code>
   */
  com.class100.service.usercenter.Reply_MySchoolmateOrBuilder getMyschoolmateOrBuilder(
      int index);
}
