// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

public interface ReplyStudentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.ReplyStudents)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string code = 2;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>repeated .custom_proto.RequestRStudentStruct sls = 3;</code>
   */
  java.util.List<com.class100.service.usercenter.RequestRStudentStruct> 
      getSlsList();
  /**
   * <code>repeated .custom_proto.RequestRStudentStruct sls = 3;</code>
   */
  com.class100.service.usercenter.RequestRStudentStruct getSls(int index);
  /**
   * <code>repeated .custom_proto.RequestRStudentStruct sls = 3;</code>
   */
  int getSlsCount();
  /**
   * <code>repeated .custom_proto.RequestRStudentStruct sls = 3;</code>
   */
  java.util.List<? extends com.class100.service.usercenter.RequestRStudentStructOrBuilder> 
      getSlsOrBuilderList();
  /**
   * <code>repeated .custom_proto.RequestRStudentStruct sls = 3;</code>
   */
  com.class100.service.usercenter.RequestRStudentStructOrBuilder getSlsOrBuilder(
      int index);
}
