// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

public interface ReqGetSchoolProvinceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.ReqGetSchoolProvince)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 typeCode = 1;</code>
   */
  long getTypeCode();
}
