// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

public interface ReqGetStudentByLoginNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.ReqGetStudentByLoginName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string loginName = 1;</code>
   */
  java.lang.String getLoginName();
  /**
   * <code>string loginName = 1;</code>
   */
  com.google.protobuf.ByteString
      getLoginNameBytes();
}
