// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

public interface ReqGetCityByProvinceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.ReqGetCityByProvince)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 typeCode = 1;</code>
   */
  long getTypeCode();

  /**
   * <code>string province = 2;</code>
   */
  java.lang.String getProvince();
  /**
   * <code>string province = 2;</code>
   */
  com.google.protobuf.ByteString
      getProvinceBytes();
}
