// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

/**
 * Protobuf type {@code custom_proto.ReqGetClassBySchoolD}
 */
public  final class ReqGetClassBySchoolD extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:custom_proto.ReqGetClassBySchoolD)
    ReqGetClassBySchoolDOrBuilder {
  // Use ReqGetClassBySchoolD.newBuilder() to construct.
  private ReqGetClassBySchoolD(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReqGetClassBySchoolD() {
    schoolName_ = "";
    gradeId_ = 0L;
    classId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ReqGetClassBySchoolD(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            schoolName_ = s;
            break;
          }
          case 16: {

            gradeId_ = input.readInt64();
            break;
          }
          case 24: {

            classId_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_ReqGetClassBySchoolD_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_ReqGetClassBySchoolD_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.class100.service.usercenter.ReqGetClassBySchoolD.class, com.class100.service.usercenter.ReqGetClassBySchoolD.Builder.class);
  }

  public static final int SCHOOLNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object schoolName_;
  /**
   * <code>string SchoolName = 1;</code>
   */
  public java.lang.String getSchoolName() {
    java.lang.Object ref = schoolName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      schoolName_ = s;
      return s;
    }
  }
  /**
   * <code>string SchoolName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSchoolNameBytes() {
    java.lang.Object ref = schoolName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      schoolName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GRADEID_FIELD_NUMBER = 2;
  private long gradeId_;
  /**
   * <code>int64 GradeId = 2;</code>
   */
  public long getGradeId() {
    return gradeId_;
  }

  public static final int CLASSID_FIELD_NUMBER = 3;
  private long classId_;
  /**
   * <code>int64 ClassId = 3;</code>
   */
  public long getClassId() {
    return classId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSchoolNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, schoolName_);
    }
    if (gradeId_ != 0L) {
      output.writeInt64(2, gradeId_);
    }
    if (classId_ != 0L) {
      output.writeInt64(3, classId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSchoolNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, schoolName_);
    }
    if (gradeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, gradeId_);
    }
    if (classId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, classId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.class100.service.usercenter.ReqGetClassBySchoolD)) {
      return super.equals(obj);
    }
    com.class100.service.usercenter.ReqGetClassBySchoolD other = (com.class100.service.usercenter.ReqGetClassBySchoolD) obj;

    boolean result = true;
    result = result && getSchoolName()
        .equals(other.getSchoolName());
    result = result && (getGradeId()
        == other.getGradeId());
    result = result && (getClassId()
        == other.getClassId());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCHOOLNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSchoolName().hashCode();
    hash = (37 * hash) + GRADEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGradeId());
    hash = (37 * hash) + CLASSID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getClassId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.class100.service.usercenter.ReqGetClassBySchoolD parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.class100.service.usercenter.ReqGetClassBySchoolD parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.class100.service.usercenter.ReqGetClassBySchoolD parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.class100.service.usercenter.ReqGetClassBySchoolD parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.class100.service.usercenter.ReqGetClassBySchoolD parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.class100.service.usercenter.ReqGetClassBySchoolD parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.class100.service.usercenter.ReqGetClassBySchoolD parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.class100.service.usercenter.ReqGetClassBySchoolD parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.class100.service.usercenter.ReqGetClassBySchoolD parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.class100.service.usercenter.ReqGetClassBySchoolD parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.class100.service.usercenter.ReqGetClassBySchoolD prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code custom_proto.ReqGetClassBySchoolD}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:custom_proto.ReqGetClassBySchoolD)
      com.class100.service.usercenter.ReqGetClassBySchoolDOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_ReqGetClassBySchoolD_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_ReqGetClassBySchoolD_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.class100.service.usercenter.ReqGetClassBySchoolD.class, com.class100.service.usercenter.ReqGetClassBySchoolD.Builder.class);
    }

    // Construct using com.class100.service.usercenter.ReqGetClassBySchoolD.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      schoolName_ = "";

      gradeId_ = 0L;

      classId_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_ReqGetClassBySchoolD_descriptor;
    }

    public com.class100.service.usercenter.ReqGetClassBySchoolD getDefaultInstanceForType() {
      return com.class100.service.usercenter.ReqGetClassBySchoolD.getDefaultInstance();
    }

    public com.class100.service.usercenter.ReqGetClassBySchoolD build() {
      com.class100.service.usercenter.ReqGetClassBySchoolD result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.class100.service.usercenter.ReqGetClassBySchoolD buildPartial() {
      com.class100.service.usercenter.ReqGetClassBySchoolD result = new com.class100.service.usercenter.ReqGetClassBySchoolD(this);
      result.schoolName_ = schoolName_;
      result.gradeId_ = gradeId_;
      result.classId_ = classId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.class100.service.usercenter.ReqGetClassBySchoolD) {
        return mergeFrom((com.class100.service.usercenter.ReqGetClassBySchoolD)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.class100.service.usercenter.ReqGetClassBySchoolD other) {
      if (other == com.class100.service.usercenter.ReqGetClassBySchoolD.getDefaultInstance()) return this;
      if (!other.getSchoolName().isEmpty()) {
        schoolName_ = other.schoolName_;
        onChanged();
      }
      if (other.getGradeId() != 0L) {
        setGradeId(other.getGradeId());
      }
      if (other.getClassId() != 0L) {
        setClassId(other.getClassId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.class100.service.usercenter.ReqGetClassBySchoolD parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.class100.service.usercenter.ReqGetClassBySchoolD) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object schoolName_ = "";
    /**
     * <code>string SchoolName = 1;</code>
     */
    public java.lang.String getSchoolName() {
      java.lang.Object ref = schoolName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schoolName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string SchoolName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSchoolNameBytes() {
      java.lang.Object ref = schoolName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schoolName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string SchoolName = 1;</code>
     */
    public Builder setSchoolName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      schoolName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string SchoolName = 1;</code>
     */
    public Builder clearSchoolName() {
      
      schoolName_ = getDefaultInstance().getSchoolName();
      onChanged();
      return this;
    }
    /**
     * <code>string SchoolName = 1;</code>
     */
    public Builder setSchoolNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      schoolName_ = value;
      onChanged();
      return this;
    }

    private long gradeId_ ;
    /**
     * <code>int64 GradeId = 2;</code>
     */
    public long getGradeId() {
      return gradeId_;
    }
    /**
     * <code>int64 GradeId = 2;</code>
     */
    public Builder setGradeId(long value) {
      
      gradeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 GradeId = 2;</code>
     */
    public Builder clearGradeId() {
      
      gradeId_ = 0L;
      onChanged();
      return this;
    }

    private long classId_ ;
    /**
     * <code>int64 ClassId = 3;</code>
     */
    public long getClassId() {
      return classId_;
    }
    /**
     * <code>int64 ClassId = 3;</code>
     */
    public Builder setClassId(long value) {
      
      classId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ClassId = 3;</code>
     */
    public Builder clearClassId() {
      
      classId_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:custom_proto.ReqGetClassBySchoolD)
  }

  // @@protoc_insertion_point(class_scope:custom_proto.ReqGetClassBySchoolD)
  private static final com.class100.service.usercenter.ReqGetClassBySchoolD DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.class100.service.usercenter.ReqGetClassBySchoolD();
  }

  public static com.class100.service.usercenter.ReqGetClassBySchoolD getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReqGetClassBySchoolD>
      PARSER = new com.google.protobuf.AbstractParser<ReqGetClassBySchoolD>() {
    public ReqGetClassBySchoolD parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqGetClassBySchoolD(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReqGetClassBySchoolD> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReqGetClassBySchoolD> getParserForType() {
    return PARSER;
  }

  public com.class100.service.usercenter.ReqGetClassBySchoolD getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

