// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

public interface RequestGetClassesStructOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.RequestGetClassesStruct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 schoolid = 1;</code>
   */
  long getSchoolid();

  /**
   * <code>int64 classid = 2;</code>
   */
  long getClassid();
}
