// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

public interface RequestGetTeasOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.RequestGetTeas)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 pageSize = 1;</code>
   */
  long getPageSize();

  /**
   * <pre>
   * 搜索条件
   * </pre>
   *
   * <code>int64 currentPage = 2;</code>
   */
  long getCurrentPage();
}
