// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

/**
 * Protobuf type {@code custom_proto.RequestStudentScreen}
 */
public  final class RequestStudentScreen extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:custom_proto.RequestStudentScreen)
    RequestStudentScreenOrBuilder {
  // Use RequestStudentScreen.newBuilder() to construct.
  private RequestStudentScreen(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestStudentScreen() {
    studentName_ = "";
    schID_ = 0L;
    claID_ = 0L;
    page_ = 0L;
    pageSize_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RequestStudentScreen(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            studentName_ = s;
            break;
          }
          case 16: {

            schID_ = input.readInt64();
            break;
          }
          case 24: {

            claID_ = input.readInt64();
            break;
          }
          case 32: {

            page_ = input.readInt64();
            break;
          }
          case 40: {

            pageSize_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestStudentScreen_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestStudentScreen_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.class100.service.usercenter.RequestStudentScreen.class, com.class100.service.usercenter.RequestStudentScreen.Builder.class);
  }

  public static final int STUDENTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object studentName_;
  /**
   * <code>string studentName = 1;</code>
   */
  public java.lang.String getStudentName() {
    java.lang.Object ref = studentName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      studentName_ = s;
      return s;
    }
  }
  /**
   * <code>string studentName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStudentNameBytes() {
    java.lang.Object ref = studentName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      studentName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCHID_FIELD_NUMBER = 2;
  private long schID_;
  /**
   * <code>int64 schID = 2;</code>
   */
  public long getSchID() {
    return schID_;
  }

  public static final int CLAID_FIELD_NUMBER = 3;
  private long claID_;
  /**
   * <code>int64 claID = 3;</code>
   */
  public long getClaID() {
    return claID_;
  }

  public static final int PAGE_FIELD_NUMBER = 4;
  private long page_;
  /**
   * <code>int64 page = 4;</code>
   */
  public long getPage() {
    return page_;
  }

  public static final int PAGESIZE_FIELD_NUMBER = 5;
  private long pageSize_;
  /**
   * <code>int64 pageSize = 5;</code>
   */
  public long getPageSize() {
    return pageSize_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStudentNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, studentName_);
    }
    if (schID_ != 0L) {
      output.writeInt64(2, schID_);
    }
    if (claID_ != 0L) {
      output.writeInt64(3, claID_);
    }
    if (page_ != 0L) {
      output.writeInt64(4, page_);
    }
    if (pageSize_ != 0L) {
      output.writeInt64(5, pageSize_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStudentNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, studentName_);
    }
    if (schID_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, schID_);
    }
    if (claID_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, claID_);
    }
    if (page_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, page_);
    }
    if (pageSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, pageSize_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.class100.service.usercenter.RequestStudentScreen)) {
      return super.equals(obj);
    }
    com.class100.service.usercenter.RequestStudentScreen other = (com.class100.service.usercenter.RequestStudentScreen) obj;

    boolean result = true;
    result = result && getStudentName()
        .equals(other.getStudentName());
    result = result && (getSchID()
        == other.getSchID());
    result = result && (getClaID()
        == other.getClaID());
    result = result && (getPage()
        == other.getPage());
    result = result && (getPageSize()
        == other.getPageSize());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STUDENTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getStudentName().hashCode();
    hash = (37 * hash) + SCHID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSchID());
    hash = (37 * hash) + CLAID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getClaID());
    hash = (37 * hash) + PAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPage());
    hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPageSize());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.class100.service.usercenter.RequestStudentScreen parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.class100.service.usercenter.RequestStudentScreen parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.class100.service.usercenter.RequestStudentScreen parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.class100.service.usercenter.RequestStudentScreen parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.class100.service.usercenter.RequestStudentScreen parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.class100.service.usercenter.RequestStudentScreen parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.class100.service.usercenter.RequestStudentScreen parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.class100.service.usercenter.RequestStudentScreen parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.class100.service.usercenter.RequestStudentScreen parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.class100.service.usercenter.RequestStudentScreen parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.class100.service.usercenter.RequestStudentScreen prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code custom_proto.RequestStudentScreen}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:custom_proto.RequestStudentScreen)
      com.class100.service.usercenter.RequestStudentScreenOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestStudentScreen_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestStudentScreen_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.class100.service.usercenter.RequestStudentScreen.class, com.class100.service.usercenter.RequestStudentScreen.Builder.class);
    }

    // Construct using com.class100.service.usercenter.RequestStudentScreen.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      studentName_ = "";

      schID_ = 0L;

      claID_ = 0L;

      page_ = 0L;

      pageSize_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestStudentScreen_descriptor;
    }

    public com.class100.service.usercenter.RequestStudentScreen getDefaultInstanceForType() {
      return com.class100.service.usercenter.RequestStudentScreen.getDefaultInstance();
    }

    public com.class100.service.usercenter.RequestStudentScreen build() {
      com.class100.service.usercenter.RequestStudentScreen result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.class100.service.usercenter.RequestStudentScreen buildPartial() {
      com.class100.service.usercenter.RequestStudentScreen result = new com.class100.service.usercenter.RequestStudentScreen(this);
      result.studentName_ = studentName_;
      result.schID_ = schID_;
      result.claID_ = claID_;
      result.page_ = page_;
      result.pageSize_ = pageSize_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.class100.service.usercenter.RequestStudentScreen) {
        return mergeFrom((com.class100.service.usercenter.RequestStudentScreen)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.class100.service.usercenter.RequestStudentScreen other) {
      if (other == com.class100.service.usercenter.RequestStudentScreen.getDefaultInstance()) return this;
      if (!other.getStudentName().isEmpty()) {
        studentName_ = other.studentName_;
        onChanged();
      }
      if (other.getSchID() != 0L) {
        setSchID(other.getSchID());
      }
      if (other.getClaID() != 0L) {
        setClaID(other.getClaID());
      }
      if (other.getPage() != 0L) {
        setPage(other.getPage());
      }
      if (other.getPageSize() != 0L) {
        setPageSize(other.getPageSize());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.class100.service.usercenter.RequestStudentScreen parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.class100.service.usercenter.RequestStudentScreen) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object studentName_ = "";
    /**
     * <code>string studentName = 1;</code>
     */
    public java.lang.String getStudentName() {
      java.lang.Object ref = studentName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studentName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string studentName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStudentNameBytes() {
      java.lang.Object ref = studentName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studentName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string studentName = 1;</code>
     */
    public Builder setStudentName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      studentName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string studentName = 1;</code>
     */
    public Builder clearStudentName() {
      
      studentName_ = getDefaultInstance().getStudentName();
      onChanged();
      return this;
    }
    /**
     * <code>string studentName = 1;</code>
     */
    public Builder setStudentNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      studentName_ = value;
      onChanged();
      return this;
    }

    private long schID_ ;
    /**
     * <code>int64 schID = 2;</code>
     */
    public long getSchID() {
      return schID_;
    }
    /**
     * <code>int64 schID = 2;</code>
     */
    public Builder setSchID(long value) {
      
      schID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 schID = 2;</code>
     */
    public Builder clearSchID() {
      
      schID_ = 0L;
      onChanged();
      return this;
    }

    private long claID_ ;
    /**
     * <code>int64 claID = 3;</code>
     */
    public long getClaID() {
      return claID_;
    }
    /**
     * <code>int64 claID = 3;</code>
     */
    public Builder setClaID(long value) {
      
      claID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 claID = 3;</code>
     */
    public Builder clearClaID() {
      
      claID_ = 0L;
      onChanged();
      return this;
    }

    private long page_ ;
    /**
     * <code>int64 page = 4;</code>
     */
    public long getPage() {
      return page_;
    }
    /**
     * <code>int64 page = 4;</code>
     */
    public Builder setPage(long value) {
      
      page_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 page = 4;</code>
     */
    public Builder clearPage() {
      
      page_ = 0L;
      onChanged();
      return this;
    }

    private long pageSize_ ;
    /**
     * <code>int64 pageSize = 5;</code>
     */
    public long getPageSize() {
      return pageSize_;
    }
    /**
     * <code>int64 pageSize = 5;</code>
     */
    public Builder setPageSize(long value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 pageSize = 5;</code>
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:custom_proto.RequestStudentScreen)
  }

  // @@protoc_insertion_point(class_scope:custom_proto.RequestStudentScreen)
  private static final com.class100.service.usercenter.RequestStudentScreen DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.class100.service.usercenter.RequestStudentScreen();
  }

  public static com.class100.service.usercenter.RequestStudentScreen getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestStudentScreen>
      PARSER = new com.google.protobuf.AbstractParser<RequestStudentScreen>() {
    public RequestStudentScreen parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestStudentScreen(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestStudentScreen> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestStudentScreen> getParserForType() {
    return PARSER;
  }

  public com.class100.service.usercenter.RequestStudentScreen getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

