// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

/**
 * Protobuf type {@code custom_proto.RequestRSchoolStruct}
 */
public  final class RequestRSchoolStruct extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:custom_proto.RequestRSchoolStruct)
    RequestRSchoolStructOrBuilder {
  // Use RequestRSchoolStruct.newBuilder() to construct.
  private RequestRSchoolStruct(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestRSchoolStruct() {
    id_ = 0L;
    loginName_ = "";
    password_ = "";
    schoolname_ = "";
    regionId_ = 0L;
    regionName_ = "";
    city_ = "";
    province_ = "";
    grades_ = java.util.Collections.emptyList();
    sgrades_ = "";
    phone_ = 0L;
    type_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RequestRSchoolStruct(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            loginName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            schoolname_ = s;
            break;
          }
          case 40: {

            regionId_ = input.readInt64();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            regionName_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            province_ = s;
            break;
          }
          case 72: {
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              grades_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000100;
            }
            grades_.add(input.readInt64());
            break;
          }
          case 74: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100) && input.getBytesUntilLimit() > 0) {
              grades_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000100;
            }
            while (input.getBytesUntilLimit() > 0) {
              grades_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            sgrades_ = s;
            break;
          }
          case 88: {

            phone_ = input.readInt64();
            break;
          }
          case 96: {

            type_ = input.readInt64();
            break;
          }
          case 106: {
            if (!((mutable_bitField0_ & 0x00001000) == 0x00001000)) {
              gradesKV_ = com.google.protobuf.MapField.newMapField(
                  GradesKVDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00001000;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            gradesKV__ = input.readMessage(
                GradesKVDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            gradesKV_.getMutableMap().put(
                gradesKV__.getKey(), gradesKV__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        grades_ = java.util.Collections.unmodifiableList(grades_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestRSchoolStruct_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 13:
        return internalGetGradesKV();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestRSchoolStruct_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.class100.service.usercenter.RequestRSchoolStruct.class, com.class100.service.usercenter.RequestRSchoolStruct.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int LOGINNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object loginName_;
  /**
   * <code>string loginName = 2;</code>
   */
  public java.lang.String getLoginName() {
    java.lang.Object ref = loginName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      loginName_ = s;
      return s;
    }
  }
  /**
   * <code>string loginName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLoginNameBytes() {
    java.lang.Object ref = loginName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      loginName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object password_;
  /**
   * <code>string password = 3;</code>
   */
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCHOOLNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object schoolname_;
  /**
   * <code>string schoolname = 4;</code>
   */
  public java.lang.String getSchoolname() {
    java.lang.Object ref = schoolname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      schoolname_ = s;
      return s;
    }
  }
  /**
   * <code>string schoolname = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSchoolnameBytes() {
    java.lang.Object ref = schoolname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      schoolname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REGIONID_FIELD_NUMBER = 5;
  private long regionId_;
  /**
   * <code>int64 regionId = 5;</code>
   */
  public long getRegionId() {
    return regionId_;
  }

  public static final int REGION_NAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object regionName_;
  /**
   * <code>string region_name = 6;</code>
   */
  public java.lang.String getRegionName() {
    java.lang.Object ref = regionName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      regionName_ = s;
      return s;
    }
  }
  /**
   * <code>string region_name = 6;</code>
   */
  public com.google.protobuf.ByteString
      getRegionNameBytes() {
    java.lang.Object ref = regionName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      regionName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITY_FIELD_NUMBER = 7;
  private volatile java.lang.Object city_;
  /**
   * <code>string city = 7;</code>
   */
  public java.lang.String getCity() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <code>string city = 7;</code>
   */
  public com.google.protobuf.ByteString
      getCityBytes() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVINCE_FIELD_NUMBER = 8;
  private volatile java.lang.Object province_;
  /**
   * <code>string province = 8;</code>
   */
  public java.lang.String getProvince() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      province_ = s;
      return s;
    }
  }
  /**
   * <code>string province = 8;</code>
   */
  public com.google.protobuf.ByteString
      getProvinceBytes() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      province_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GRADES_FIELD_NUMBER = 9;
  private java.util.List<java.lang.Long> grades_;
  /**
   * <code>repeated int64 grades = 9;</code>
   */
  public java.util.List<java.lang.Long>
      getGradesList() {
    return grades_;
  }
  /**
   * <code>repeated int64 grades = 9;</code>
   */
  public int getGradesCount() {
    return grades_.size();
  }
  /**
   * <code>repeated int64 grades = 9;</code>
   */
  public long getGrades(int index) {
    return grades_.get(index);
  }
  private int gradesMemoizedSerializedSize = -1;

  public static final int SGRADES_FIELD_NUMBER = 10;
  private volatile java.lang.Object sgrades_;
  /**
   * <code>string sgrades = 10;</code>
   */
  public java.lang.String getSgrades() {
    java.lang.Object ref = sgrades_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sgrades_ = s;
      return s;
    }
  }
  /**
   * <code>string sgrades = 10;</code>
   */
  public com.google.protobuf.ByteString
      getSgradesBytes() {
    java.lang.Object ref = sgrades_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sgrades_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE_FIELD_NUMBER = 11;
  private long phone_;
  /**
   * <code>int64 phone = 11;</code>
   */
  public long getPhone() {
    return phone_;
  }

  public static final int TYPE_FIELD_NUMBER = 12;
  private long type_;
  /**
   * <code>int64 type = 12;</code>
   */
  public long getType() {
    return type_;
  }

  public static final int GRADESKV_FIELD_NUMBER = 13;
  private static final class GradesKVDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestRSchoolStruct_GradesKVEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> gradesKV_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetGradesKV() {
    if (gradesKV_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          GradesKVDefaultEntryHolder.defaultEntry);
    }
    return gradesKV_;
  }

  public int getGradesKVCount() {
    return internalGetGradesKV().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; GradesKV = 13;</code>
   */

  public boolean containsGradesKV(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetGradesKV().getMap().containsKey(key);
  }
  /**
   * Use {@link #getGradesKVMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getGradesKV() {
    return getGradesKVMap();
  }
  /**
   * <code>map&lt;string, string&gt; GradesKV = 13;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getGradesKVMap() {
    return internalGetGradesKV().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; GradesKV = 13;</code>
   */

  public java.lang.String getGradesKVOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetGradesKV().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; GradesKV = 13;</code>
   */

  public java.lang.String getGradesKVOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetGradesKV().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getLoginNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, loginName_);
    }
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    if (!getSchoolnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, schoolname_);
    }
    if (regionId_ != 0L) {
      output.writeInt64(5, regionId_);
    }
    if (!getRegionNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, regionName_);
    }
    if (!getCityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, city_);
    }
    if (!getProvinceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, province_);
    }
    if (getGradesList().size() > 0) {
      output.writeUInt32NoTag(74);
      output.writeUInt32NoTag(gradesMemoizedSerializedSize);
    }
    for (int i = 0; i < grades_.size(); i++) {
      output.writeInt64NoTag(grades_.get(i));
    }
    if (!getSgradesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, sgrades_);
    }
    if (phone_ != 0L) {
      output.writeInt64(11, phone_);
    }
    if (type_ != 0L) {
      output.writeInt64(12, type_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetGradesKV(),
        GradesKVDefaultEntryHolder.defaultEntry,
        13);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getLoginNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, loginName_);
    }
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    if (!getSchoolnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, schoolname_);
    }
    if (regionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, regionId_);
    }
    if (!getRegionNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, regionName_);
    }
    if (!getCityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, city_);
    }
    if (!getProvinceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, province_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < grades_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(grades_.get(i));
      }
      size += dataSize;
      if (!getGradesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      gradesMemoizedSerializedSize = dataSize;
    }
    if (!getSgradesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, sgrades_);
    }
    if (phone_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, phone_);
    }
    if (type_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, type_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetGradesKV().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      gradesKV__ = GradesKVDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, gradesKV__);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.class100.service.usercenter.RequestRSchoolStruct)) {
      return super.equals(obj);
    }
    com.class100.service.usercenter.RequestRSchoolStruct other = (com.class100.service.usercenter.RequestRSchoolStruct) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getLoginName()
        .equals(other.getLoginName());
    result = result && getPassword()
        .equals(other.getPassword());
    result = result && getSchoolname()
        .equals(other.getSchoolname());
    result = result && (getRegionId()
        == other.getRegionId());
    result = result && getRegionName()
        .equals(other.getRegionName());
    result = result && getCity()
        .equals(other.getCity());
    result = result && getProvince()
        .equals(other.getProvince());
    result = result && getGradesList()
        .equals(other.getGradesList());
    result = result && getSgrades()
        .equals(other.getSgrades());
    result = result && (getPhone()
        == other.getPhone());
    result = result && (getType()
        == other.getType());
    result = result && internalGetGradesKV().equals(
        other.internalGetGradesKV());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + LOGINNAME_FIELD_NUMBER;
    hash = (53 * hash) + getLoginName().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + SCHOOLNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSchoolname().hashCode();
    hash = (37 * hash) + REGIONID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRegionId());
    hash = (37 * hash) + REGION_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getRegionName().hashCode();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
    hash = (53 * hash) + getProvince().hashCode();
    if (getGradesCount() > 0) {
      hash = (37 * hash) + GRADES_FIELD_NUMBER;
      hash = (53 * hash) + getGradesList().hashCode();
    }
    hash = (37 * hash) + SGRADES_FIELD_NUMBER;
    hash = (53 * hash) + getSgrades().hashCode();
    hash = (37 * hash) + PHONE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPhone());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getType());
    if (!internalGetGradesKV().getMap().isEmpty()) {
      hash = (37 * hash) + GRADESKV_FIELD_NUMBER;
      hash = (53 * hash) + internalGetGradesKV().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.class100.service.usercenter.RequestRSchoolStruct parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.class100.service.usercenter.RequestRSchoolStruct parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.class100.service.usercenter.RequestRSchoolStruct parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.class100.service.usercenter.RequestRSchoolStruct parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.class100.service.usercenter.RequestRSchoolStruct parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.class100.service.usercenter.RequestRSchoolStruct parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.class100.service.usercenter.RequestRSchoolStruct parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.class100.service.usercenter.RequestRSchoolStruct parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.class100.service.usercenter.RequestRSchoolStruct parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.class100.service.usercenter.RequestRSchoolStruct parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.class100.service.usercenter.RequestRSchoolStruct prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code custom_proto.RequestRSchoolStruct}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:custom_proto.RequestRSchoolStruct)
      com.class100.service.usercenter.RequestRSchoolStructOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestRSchoolStruct_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 13:
          return internalGetGradesKV();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 13:
          return internalGetMutableGradesKV();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestRSchoolStruct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.class100.service.usercenter.RequestRSchoolStruct.class, com.class100.service.usercenter.RequestRSchoolStruct.Builder.class);
    }

    // Construct using com.class100.service.usercenter.RequestRSchoolStruct.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      loginName_ = "";

      password_ = "";

      schoolname_ = "";

      regionId_ = 0L;

      regionName_ = "";

      city_ = "";

      province_ = "";

      grades_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000100);
      sgrades_ = "";

      phone_ = 0L;

      type_ = 0L;

      internalGetMutableGradesKV().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestRSchoolStruct_descriptor;
    }

    public com.class100.service.usercenter.RequestRSchoolStruct getDefaultInstanceForType() {
      return com.class100.service.usercenter.RequestRSchoolStruct.getDefaultInstance();
    }

    public com.class100.service.usercenter.RequestRSchoolStruct build() {
      com.class100.service.usercenter.RequestRSchoolStruct result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.class100.service.usercenter.RequestRSchoolStruct buildPartial() {
      com.class100.service.usercenter.RequestRSchoolStruct result = new com.class100.service.usercenter.RequestRSchoolStruct(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.loginName_ = loginName_;
      result.password_ = password_;
      result.schoolname_ = schoolname_;
      result.regionId_ = regionId_;
      result.regionName_ = regionName_;
      result.city_ = city_;
      result.province_ = province_;
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        grades_ = java.util.Collections.unmodifiableList(grades_);
        bitField0_ = (bitField0_ & ~0x00000100);
      }
      result.grades_ = grades_;
      result.sgrades_ = sgrades_;
      result.phone_ = phone_;
      result.type_ = type_;
      result.gradesKV_ = internalGetGradesKV();
      result.gradesKV_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.class100.service.usercenter.RequestRSchoolStruct) {
        return mergeFrom((com.class100.service.usercenter.RequestRSchoolStruct)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.class100.service.usercenter.RequestRSchoolStruct other) {
      if (other == com.class100.service.usercenter.RequestRSchoolStruct.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getLoginName().isEmpty()) {
        loginName_ = other.loginName_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (!other.getSchoolname().isEmpty()) {
        schoolname_ = other.schoolname_;
        onChanged();
      }
      if (other.getRegionId() != 0L) {
        setRegionId(other.getRegionId());
      }
      if (!other.getRegionName().isEmpty()) {
        regionName_ = other.regionName_;
        onChanged();
      }
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (!other.getProvince().isEmpty()) {
        province_ = other.province_;
        onChanged();
      }
      if (!other.grades_.isEmpty()) {
        if (grades_.isEmpty()) {
          grades_ = other.grades_;
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          ensureGradesIsMutable();
          grades_.addAll(other.grades_);
        }
        onChanged();
      }
      if (!other.getSgrades().isEmpty()) {
        sgrades_ = other.sgrades_;
        onChanged();
      }
      if (other.getPhone() != 0L) {
        setPhone(other.getPhone());
      }
      if (other.getType() != 0L) {
        setType(other.getType());
      }
      internalGetMutableGradesKV().mergeFrom(
          other.internalGetGradesKV());
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.class100.service.usercenter.RequestRSchoolStruct parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.class100.service.usercenter.RequestRSchoolStruct) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object loginName_ = "";
    /**
     * <code>string loginName = 2;</code>
     */
    public java.lang.String getLoginName() {
      java.lang.Object ref = loginName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loginName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string loginName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLoginNameBytes() {
      java.lang.Object ref = loginName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string loginName = 2;</code>
     */
    public Builder setLoginName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      loginName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string loginName = 2;</code>
     */
    public Builder clearLoginName() {
      
      loginName_ = getDefaultInstance().getLoginName();
      onChanged();
      return this;
    }
    /**
     * <code>string loginName = 2;</code>
     */
    public Builder setLoginNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      loginName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object schoolname_ = "";
    /**
     * <code>string schoolname = 4;</code>
     */
    public java.lang.String getSchoolname() {
      java.lang.Object ref = schoolname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schoolname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string schoolname = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSchoolnameBytes() {
      java.lang.Object ref = schoolname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schoolname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string schoolname = 4;</code>
     */
    public Builder setSchoolname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      schoolname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string schoolname = 4;</code>
     */
    public Builder clearSchoolname() {
      
      schoolname_ = getDefaultInstance().getSchoolname();
      onChanged();
      return this;
    }
    /**
     * <code>string schoolname = 4;</code>
     */
    public Builder setSchoolnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      schoolname_ = value;
      onChanged();
      return this;
    }

    private long regionId_ ;
    /**
     * <code>int64 regionId = 5;</code>
     */
    public long getRegionId() {
      return regionId_;
    }
    /**
     * <code>int64 regionId = 5;</code>
     */
    public Builder setRegionId(long value) {
      
      regionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 regionId = 5;</code>
     */
    public Builder clearRegionId() {
      
      regionId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object regionName_ = "";
    /**
     * <code>string region_name = 6;</code>
     */
    public java.lang.String getRegionName() {
      java.lang.Object ref = regionName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        regionName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string region_name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getRegionNameBytes() {
      java.lang.Object ref = regionName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        regionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string region_name = 6;</code>
     */
    public Builder setRegionName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      regionName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string region_name = 6;</code>
     */
    public Builder clearRegionName() {
      
      regionName_ = getDefaultInstance().getRegionName();
      onChanged();
      return this;
    }
    /**
     * <code>string region_name = 6;</code>
     */
    public Builder setRegionNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      regionName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object city_ = "";
    /**
     * <code>string city = 7;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string city = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string city = 7;</code>
     */
    public Builder setCity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string city = 7;</code>
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <code>string city = 7;</code>
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object province_ = "";
    /**
     * <code>string province = 8;</code>
     */
    public java.lang.String getProvince() {
      java.lang.Object ref = province_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        province_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string province = 8;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      java.lang.Object ref = province_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string province = 8;</code>
     */
    public Builder setProvince(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      province_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string province = 8;</code>
     */
    public Builder clearProvince() {
      
      province_ = getDefaultInstance().getProvince();
      onChanged();
      return this;
    }
    /**
     * <code>string province = 8;</code>
     */
    public Builder setProvinceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      province_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Long> grades_ = java.util.Collections.emptyList();
    private void ensureGradesIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        grades_ = new java.util.ArrayList<java.lang.Long>(grades_);
        bitField0_ |= 0x00000100;
       }
    }
    /**
     * <code>repeated int64 grades = 9;</code>
     */
    public java.util.List<java.lang.Long>
        getGradesList() {
      return java.util.Collections.unmodifiableList(grades_);
    }
    /**
     * <code>repeated int64 grades = 9;</code>
     */
    public int getGradesCount() {
      return grades_.size();
    }
    /**
     * <code>repeated int64 grades = 9;</code>
     */
    public long getGrades(int index) {
      return grades_.get(index);
    }
    /**
     * <code>repeated int64 grades = 9;</code>
     */
    public Builder setGrades(
        int index, long value) {
      ensureGradesIsMutable();
      grades_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 grades = 9;</code>
     */
    public Builder addGrades(long value) {
      ensureGradesIsMutable();
      grades_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 grades = 9;</code>
     */
    public Builder addAllGrades(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureGradesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, grades_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 grades = 9;</code>
     */
    public Builder clearGrades() {
      grades_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }

    private java.lang.Object sgrades_ = "";
    /**
     * <code>string sgrades = 10;</code>
     */
    public java.lang.String getSgrades() {
      java.lang.Object ref = sgrades_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sgrades_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sgrades = 10;</code>
     */
    public com.google.protobuf.ByteString
        getSgradesBytes() {
      java.lang.Object ref = sgrades_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sgrades_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sgrades = 10;</code>
     */
    public Builder setSgrades(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sgrades_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sgrades = 10;</code>
     */
    public Builder clearSgrades() {
      
      sgrades_ = getDefaultInstance().getSgrades();
      onChanged();
      return this;
    }
    /**
     * <code>string sgrades = 10;</code>
     */
    public Builder setSgradesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sgrades_ = value;
      onChanged();
      return this;
    }

    private long phone_ ;
    /**
     * <code>int64 phone = 11;</code>
     */
    public long getPhone() {
      return phone_;
    }
    /**
     * <code>int64 phone = 11;</code>
     */
    public Builder setPhone(long value) {
      
      phone_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 phone = 11;</code>
     */
    public Builder clearPhone() {
      
      phone_ = 0L;
      onChanged();
      return this;
    }

    private long type_ ;
    /**
     * <code>int64 type = 12;</code>
     */
    public long getType() {
      return type_;
    }
    /**
     * <code>int64 type = 12;</code>
     */
    public Builder setType(long value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 type = 12;</code>
     */
    public Builder clearType() {
      
      type_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> gradesKV_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetGradesKV() {
      if (gradesKV_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            GradesKVDefaultEntryHolder.defaultEntry);
      }
      return gradesKV_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableGradesKV() {
      onChanged();;
      if (gradesKV_ == null) {
        gradesKV_ = com.google.protobuf.MapField.newMapField(
            GradesKVDefaultEntryHolder.defaultEntry);
      }
      if (!gradesKV_.isMutable()) {
        gradesKV_ = gradesKV_.copy();
      }
      return gradesKV_;
    }

    public int getGradesKVCount() {
      return internalGetGradesKV().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; GradesKV = 13;</code>
     */

    public boolean containsGradesKV(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetGradesKV().getMap().containsKey(key);
    }
    /**
     * Use {@link #getGradesKVMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getGradesKV() {
      return getGradesKVMap();
    }
    /**
     * <code>map&lt;string, string&gt; GradesKV = 13;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getGradesKVMap() {
      return internalGetGradesKV().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; GradesKV = 13;</code>
     */

    public java.lang.String getGradesKVOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetGradesKV().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; GradesKV = 13;</code>
     */

    public java.lang.String getGradesKVOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetGradesKV().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearGradesKV() {
      internalGetMutableGradesKV().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; GradesKV = 13;</code>
     */

    public Builder removeGradesKV(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableGradesKV().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableGradesKV() {
      return internalGetMutableGradesKV().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; GradesKV = 13;</code>
     */
    public Builder putGradesKV(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableGradesKV().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; GradesKV = 13;</code>
     */

    public Builder putAllGradesKV(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableGradesKV().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:custom_proto.RequestRSchoolStruct)
  }

  // @@protoc_insertion_point(class_scope:custom_proto.RequestRSchoolStruct)
  private static final com.class100.service.usercenter.RequestRSchoolStruct DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.class100.service.usercenter.RequestRSchoolStruct();
  }

  public static com.class100.service.usercenter.RequestRSchoolStruct getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestRSchoolStruct>
      PARSER = new com.google.protobuf.AbstractParser<RequestRSchoolStruct>() {
    public RequestRSchoolStruct parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestRSchoolStruct(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestRSchoolStruct> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestRSchoolStruct> getParserForType() {
    return PARSER;
  }

  public com.class100.service.usercenter.RequestRSchoolStruct getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

