// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

public interface Request_studentinfo_appOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.Request_studentinfo_app)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();
}
