// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

/**
 * Protobuf type {@code custom_proto.RequestGetStudentIDsBySchoolGrade}
 */
public  final class RequestGetStudentIDsBySchoolGrade extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:custom_proto.RequestGetStudentIDsBySchoolGrade)
    RequestGetStudentIDsBySchoolGradeOrBuilder {
  // Use RequestGetStudentIDsBySchoolGrade.newBuilder() to construct.
  private RequestGetStudentIDsBySchoolGrade(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestGetStudentIDsBySchoolGrade() {
    schoolId_ = 0L;
    gradeId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RequestGetStudentIDsBySchoolGrade(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            schoolId_ = input.readInt64();
            break;
          }
          case 16: {

            gradeId_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestGetStudentIDsBySchoolGrade_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestGetStudentIDsBySchoolGrade_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade.class, com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade.Builder.class);
  }

  public static final int SCHOOL_ID_FIELD_NUMBER = 1;
  private long schoolId_;
  /**
   * <code>int64 school_id = 1;</code>
   */
  public long getSchoolId() {
    return schoolId_;
  }

  public static final int GRADE_ID_FIELD_NUMBER = 2;
  private long gradeId_;
  /**
   * <code>int64 grade_id = 2;</code>
   */
  public long getGradeId() {
    return gradeId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (schoolId_ != 0L) {
      output.writeInt64(1, schoolId_);
    }
    if (gradeId_ != 0L) {
      output.writeInt64(2, gradeId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (schoolId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, schoolId_);
    }
    if (gradeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, gradeId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade)) {
      return super.equals(obj);
    }
    com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade other = (com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade) obj;

    boolean result = true;
    result = result && (getSchoolId()
        == other.getSchoolId());
    result = result && (getGradeId()
        == other.getGradeId());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCHOOL_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSchoolId());
    hash = (37 * hash) + GRADE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGradeId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code custom_proto.RequestGetStudentIDsBySchoolGrade}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:custom_proto.RequestGetStudentIDsBySchoolGrade)
      com.class100.service.usercenter.RequestGetStudentIDsBySchoolGradeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestGetStudentIDsBySchoolGrade_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestGetStudentIDsBySchoolGrade_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade.class, com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade.Builder.class);
    }

    // Construct using com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      schoolId_ = 0L;

      gradeId_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.class100.service.usercenter.UserCenterProto.internal_static_custom_proto_RequestGetStudentIDsBySchoolGrade_descriptor;
    }

    public com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade getDefaultInstanceForType() {
      return com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade.getDefaultInstance();
    }

    public com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade build() {
      com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade buildPartial() {
      com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade result = new com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade(this);
      result.schoolId_ = schoolId_;
      result.gradeId_ = gradeId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade) {
        return mergeFrom((com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade other) {
      if (other == com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade.getDefaultInstance()) return this;
      if (other.getSchoolId() != 0L) {
        setSchoolId(other.getSchoolId());
      }
      if (other.getGradeId() != 0L) {
        setGradeId(other.getGradeId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long schoolId_ ;
    /**
     * <code>int64 school_id = 1;</code>
     */
    public long getSchoolId() {
      return schoolId_;
    }
    /**
     * <code>int64 school_id = 1;</code>
     */
    public Builder setSchoolId(long value) {
      
      schoolId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 school_id = 1;</code>
     */
    public Builder clearSchoolId() {
      
      schoolId_ = 0L;
      onChanged();
      return this;
    }

    private long gradeId_ ;
    /**
     * <code>int64 grade_id = 2;</code>
     */
    public long getGradeId() {
      return gradeId_;
    }
    /**
     * <code>int64 grade_id = 2;</code>
     */
    public Builder setGradeId(long value) {
      
      gradeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 grade_id = 2;</code>
     */
    public Builder clearGradeId() {
      
      gradeId_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:custom_proto.RequestGetStudentIDsBySchoolGrade)
  }

  // @@protoc_insertion_point(class_scope:custom_proto.RequestGetStudentIDsBySchoolGrade)
  private static final com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade();
  }

  public static com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestGetStudentIDsBySchoolGrade>
      PARSER = new com.google.protobuf.AbstractParser<RequestGetStudentIDsBySchoolGrade>() {
    public RequestGetStudentIDsBySchoolGrade parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestGetStudentIDsBySchoolGrade(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestGetStudentIDsBySchoolGrade> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestGetStudentIDsBySchoolGrade> getParserForType() {
    return PARSER;
  }

  public com.class100.service.usercenter.RequestGetStudentIDsBySchoolGrade getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

