// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_proto.proto

package com.class100.service.usercenter;

public interface ResponseSchoolByRegionTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:custom_proto.ResponseSchoolByRegionType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string schoolname = 2;</code>
   */
  java.lang.String getSchoolname();
  /**
   * <code>string schoolname = 2;</code>
   */
  com.google.protobuf.ByteString
      getSchoolnameBytes();

  /**
   * <code>string grades = 3;</code>
   */
  java.lang.String getGrades();
  /**
   * <code>string grades = 3;</code>
   */
  com.google.protobuf.ByteString
      getGradesBytes();

  /**
   * <code>repeated int64 gradesList = 4;</code>
   */
  java.util.List<java.lang.Long> getGradesListList();
  /**
   * <code>repeated int64 gradesList = 4;</code>
   */
  int getGradesListCount();
  /**
   * <code>repeated int64 gradesList = 4;</code>
   */
  long getGradesList(int index);

  /**
   * <code>map&lt;string, string&gt; GradesKV = 5;</code>
   */
  int getGradesKVCount();
  /**
   * <code>map&lt;string, string&gt; GradesKV = 5;</code>
   */
  boolean containsGradesKV(
      java.lang.String key);
  /**
   * Use {@link #getGradesKVMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getGradesKV();
  /**
   * <code>map&lt;string, string&gt; GradesKV = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getGradesKVMap();
  /**
   * <code>map&lt;string, string&gt; GradesKV = 5;</code>
   */

  java.lang.String getGradesKVOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; GradesKV = 5;</code>
   */

  java.lang.String getGradesKVOrThrow(
      java.lang.String key);
}
